version: '3.1'
services:
  demo_db:
    container_name: demo_db
    image: postgres:14.1-alpine

    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5436:5432"